/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan.com.jframe;

import do_an.com.QuanLySV;
import do_an.com.SinhVien;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LaptopDT
 */
public class QuanLySVPanel extends javax.swing.JPanel {

    private List<SinhVien> sinhvien;
    private QuanLySV quanly = new QuanLySV();
    DefaultTableModel tblModel;

    /**
     * Creates new form QuanLySVJFrame
     */
    public QuanLySVPanel() {
        initComponents();
        sinhvien = new ArrayList<>();
        tblModel = (DefaultTableModel) jTable_InThongTinSV.getModel(); // hiển thị kết quả của bằng bảng
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_nhapMSV = new javax.swing.JTextField();
        txt_nhapHoTen = new javax.swing.JTextField();
        txt_nhapLopNC = new javax.swing.JTextField();
        txt_date = new javax.swing.JTextField();
        txt_month = new javax.swing.JTextField();
        txt_year = new javax.swing.JTextField();
        txt_nhapQue = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_InThongTinSV = new javax.swing.JTable();
        btn_New1 = new javax.swing.JButton();
        btn_Save1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_Delete1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btn_Add = new javax.swing.JButton();
        btn_Find = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Quản Lý Sinh Viên");

        jLabel16.setText(" Mã sinh viên:");

        jLabel17.setText(" Họ và tên:");

        jLabel18.setText(" Lớp niên chế:");

        jLabel19.setText(" Date of birth:");

        jLabel20.setText(" Quê quán:");

        txt_nhapMSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nhapMSVActionPerformed(evt);
            }
        });

        txt_nhapLopNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nhapLopNCActionPerformed(evt);
            }
        });

        txt_nhapQue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nhapQueActionPerformed(evt);
            }
        });

        jTable_InThongTinSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "   Mã sinh viên", "   Họ và tên", " Lớp niên chế", "   Ngày sinh", "   Quê quán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_InThongTinSV);

        btn_New1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LaptopDT\\Downloads\\iconset4\\new-icon-16.png")); // NOI18N
        btn_New1.setText("Tạo mới");
        btn_New1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_New1ActionPerformed(evt);
            }
        });

        btn_Save1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LaptopDT\\Downloads\\iconset4\\Save-icon.png")); // NOI18N
        btn_Save1.setText("Lưu");
        btn_Save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Save1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LaptopDT\\Downloads\\iconset4\\Actions-document-edit-icon-16.png")); // NOI18N
        jButton2.setText("Cập nhật");

        btn_Delete1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LaptopDT\\Downloads\\iconset4\\Actions-edit-delete-icon-16.png")); // NOI18N
        btn_Delete1.setText("Xóa");
        btn_Delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Delete1ActionPerformed(evt);
            }
        });

        btn_Add.setText("Thêm");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        btn_Find.setIcon(new javax.swing.ImageIcon("C:\\Users\\LaptopDT\\Downloads\\iconset4\\search-icon-16.png")); // NOI18N
        btn_Find.setText("Find");
        btn_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FindActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LaptopDT\\Downloads\\iconset4\\Student-3-icon.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabel16))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_nhapMSV, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                            .addComponent(txt_nhapHoTen)
                                            .addComponent(txt_nhapLopNC)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_month, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_year, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 82, Short.MAX_VALUE)))
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_nhapQue, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btn_Delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton2)
                        .addGap(39, 39, 39)
                        .addComponent(btn_Find, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(btn_New1)
                        .addGap(30, 30, 30)
                        .addComponent(btn_Save1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txt_nhapMSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txt_nhapHoTen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txt_nhapLopNC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txt_nhapQue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Find, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_New1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Save1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nhapQueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nhapQueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nhapQueActionPerformed

    private void txt_nhapMSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nhapMSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nhapMSVActionPerformed

    private void txt_nhapLopNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nhapLopNCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nhapLopNCActionPerformed

    private void btn_New1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_New1ActionPerformed
        txt_nhapMSV.setText("");
        txt_nhapHoTen.setText("");
        txt_nhapLopNC.setText("");
        txt_nhapQue.setText("");
        txt_date.setText("");
        txt_month.setText("");
        txt_year.setText("");
    }//GEN-LAST:event_btn_New1ActionPerformed

    // In danh sách lên bảng     
    public void showResult() {
        SinhVien s = sinhvien.get(sinhvien.size() - 1);
        tblModel.addRow(new Object[]{
            s.getMaSV(), s.getHoTen(), s.getTenLopNC(), s.getNgaySinh(), s.getQueQuan()
        });
    }
    private void btn_Save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Save1ActionPerformed
        try {
            SinhVien sv = new SinhVien();
            sv.setMaSV(txt_nhapMSV.getText());
            sv.setHoTen(txt_nhapHoTen.getText());
            sv.setTenLopNC(txt_nhapLopNC.getText());
            sv.setNgaySinh(LocalDate.of(Integer.parseInt(txt_year.getText()),
                    Integer.parseInt(txt_month.getText()),
                    Integer.parseInt(txt_date.getText())));
            sv.setQueQuan(txt_nhapQue.getText());
            sinhvien.add(sv);
            btn_New1ActionPerformed(evt);//Xóa trắng nội dung được hiển thị ở trên form
            showResult();// hiển thị trở lại dữ liệu trên bảng và cập nhật thông tin của sv mới
            JOptionPane.showMessageDialog(this, "Sinh viên đã được lưu!");
        } catch (Exception e) {
            e.printStackTrace(); // báo lỗi chi tiết cho mình biết
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage()); // Thông báo trên form
        }// nếu có lỗi xảy ra sẽ báo lỗi cho người dùng
    }//GEN-LAST:event_btn_Save1ActionPerformed


    private void btn_Delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Delete1ActionPerformed
        try {
            boolean isOK = quanly.xoaMaSV(txt_nhapMSV.getText());
            if (isOK == true) {
                showResult(); // Cập nhật lại giá trị bảng
                JOptionPane.showMessageDialog(this, "Đã xóa thành công sinh viên");
            } else {
                JOptionPane.showMessageDialog(this, "xóa sinh viên không thành công");
            }

        } catch (Exception e) {
            e.printStackTrace(); // báo lỗi chi tiết cho mình biết
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage()); // Thông báo trên form
        }// nếu có lỗi xảy ra sẽ báo lỗi cho người dùng*/
    }//GEN-LAST:event_btn_Delete1ActionPerformed

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        /*quanly.themThongTinSV(txt_nhapHoTen.getText(), txt_nhapMSV.getText(), txt_nhapLopNC.getText(),
            txt_nhapQue.getText(), Integer.parseInt(txt_year.getText()),
            Integer.parseInt(txt_month.getText()),
            Integer.parseInt(txt_date.getText()));*/
        String hoten = txt_nhapHoTen.getText();
        String masv = txt_nhapMSV.getText();
        String lopNC = txt_nhapLopNC.getText();
        String que = txt_nhapQue.getText();
        int d = Integer.parseInt(txt_date.getText());
        int m = Integer.parseInt(txt_month.getText());
        int y = Integer.parseInt(txt_year.getText());
        LocalDate birthday = LocalDate.of(y, m, d);
        SinhVien sv = new SinhVien(hoten, masv, lopNC, birthday, que);
        sinhvien.add(sv);
        showResult();
    }//GEN-LAST:event_btn_AddActionPerformed

    private void btn_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FindActionPerformed
        try {
            quanly.timKiemSV(txt_nhapMSV.getText());
            //    System.out.println(txt_nhapMSV.getText());
            if (quanly.timKiemSV(txt_nhapMSV.getText()) != -1) {

                SinhVien sv = new SinhVien();
                sv.setMaSV(txt_nhapMSV.getText());
                sv.setHoTen(txt_nhapHoTen.getText());
                sv.setTenLopNC(txt_nhapLopNC.getText());
                sv.setNgaySinh(LocalDate.of(Integer.parseInt(txt_year.getText()),
                        Integer.parseInt(txt_month.getText()),
                        Integer.parseInt(txt_date.getText())));
                sv.setQueQuan(txt_nhapQue.getText());
                sinhvien.add(sv);
                btn_New1ActionPerformed(evt);//Xóa trắng nội dung được hiển thị ở trên form
                showResult();// hiển thị trở lại dữ liệu trên bảng và cập nhật thông tin của sv mới
            } else {
                JOptionPane.showMessageDialog(this, "Error");
            }

        } catch (Exception e) {
            e.printStackTrace(); // báo lỗi chi tiết cho mình biết
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage()); // Thông báo trên form
        }
    }//GEN-LAST:event_btn_FindActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Delete1;
    private javax.swing.JButton btn_Find;
    private javax.swing.JButton btn_New1;
    private javax.swing.JButton btn_Save1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable_InThongTinSV;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_month;
    private javax.swing.JTextField txt_nhapHoTen;
    private javax.swing.JTextField txt_nhapLopNC;
    private javax.swing.JTextField txt_nhapMSV;
    private javax.swing.JTextField txt_nhapQue;
    private javax.swing.JTextField txt_year;
    // End of variables declaration//GEN-END:variables
}
