/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package do_an.com.jframe;

import do_an.com.QuanLySV;
import do_an.com.SinhVien;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LaptopDT
 */
public class SinhVienJFrame extends javax.swing.JFrame {

    private List<SinhVien> sinhvien;
    private QuanLySV quanly = new QuanLySV();
    DefaultTableModel tblModel;

    public SinhVienJFrame() {
        initComponents();
        setLocationRelativeTo(null); // In form ra giữa màn hình
        sinhvien = new ArrayList<>();
        tblModel = (DefaultTableModel) jTable_InThongTinSV.getModel(); // hiển thị kết quả của bằng bảng
    }

    public void initSinhVienData() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        txt_nhapMSV = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_nhapHoTen = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_nhapLopNC = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();
        txt_month = new javax.swing.JTextField();
        txt_year = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_nhapQue = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_InThongTinSV = new javax.swing.JTable();
        btn_New = new javax.swing.JButton();
        btn_Save = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        btn_Find = new javax.swing.JButton();
        btn_Open = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        btn_Add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("QUẢN LÝ SINH VIÊN");

        jLabel16.setText(" Mã sinh viên:");

        jLabel17.setText(" Họ và tên:");

        jLabel18.setText(" Lớp niên chế:");

        jLabel19.setText(" Date of birth:");

        jLabel20.setText(" Quê quán:");

        txt_nhapQue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nhapQueActionPerformed(evt);
            }
        });

        jTable_InThongTinSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "   Mã sinh viên", "   Họ và tên", " Lớp niên chế", "   Ngày sinh", "   Quê quán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_InThongTinSV);

        btn_New.setText("New");
        btn_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewActionPerformed(evt);
            }
        });

        btn_Save.setText("Save");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        btn_Delete.setText("Delete");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        btn_Find.setText("Find");
        btn_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FindActionPerformed(evt);
            }
        });

        btn_Open.setText("Open");

        btn_Exit.setText("Exit");
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        btn_Add.setText("Add");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_nhapQue, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nhapMSV, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nhapHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nhapLopNC, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_month, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_year, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_New, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Find, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Open, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_nhapMSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Add)
                    .addComponent(btn_Open))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_nhapHoTen)
                    .addComponent(btn_New)
                    .addComponent(btn_Find))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_nhapLopNC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Exit)
                    .addComponent(btn_Save))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Delete))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txt_nhapQue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nhapQueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nhapQueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nhapQueActionPerformed

    private void btn_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewActionPerformed
        txt_nhapMSV.setText("");
        txt_nhapHoTen.setText("");
        txt_nhapLopNC.setText("");
        txt_nhapQue.setText("");
        txt_date.setText("");
        txt_month.setText("");
        txt_year.setText("");
    }//GEN-LAST:event_btn_NewActionPerformed

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        /*quanly.themThongTinSV(txt_nhapHoTen.getText(), txt_nhapMSV.getText(), txt_nhapLopNC.getText(),
                txt_nhapQue.getText(), Integer.parseInt(txt_year.getText()),
                Integer.parseInt(txt_month.getText()),
                Integer.parseInt(txt_date.getText()));*/
        String hoten = txt_nhapHoTen.getText();
        String masv = txt_nhapMSV.getText();
        String lopNC = txt_nhapLopNC.getText();
        String que = txt_nhapQue.getText();
        int d = Integer.parseInt(txt_date.getText());
        int m = Integer.parseInt(txt_month.getText());
        int y = Integer.parseInt(txt_year.getText());
        LocalDate birthday = LocalDate.of(y, m, d);
        SinhVien sv = new SinhVien(hoten, masv, lopNC, birthday, que);
        sinhvien.add(sv);
        showResult();
    }//GEN-LAST:event_btn_AddActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
        try {
            SinhVien sv = new SinhVien();
            sv.setMaSV(txt_nhapMSV.getText());
            sv.setHoTen(txt_nhapHoTen.getText());
            sv.setTenLopNC(txt_nhapLopNC.getText());
            sv.setNgaySinh(LocalDate.of(Integer.parseInt(txt_year.getText()),
                    Integer.parseInt(txt_month.getText()),
                    Integer.parseInt(txt_date.getText())));
            sv.setQueQuan(txt_nhapQue.getText());
            sinhvien.add(sv);
            btn_NewActionPerformed(evt);//Xóa trắng nội dung được hiển thị ở trên form
            showResult();// hiển thị trở lại dữ liệu trên bảng và cập nhật thông tin của sv mới
            JOptionPane.showMessageDialog(this, "Sinh viên đã được lưu!");
        } catch (Exception e) {
            e.printStackTrace(); // báo lỗi chi tiết cho mình biết
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage()); // Thông báo trên form
        }// nếu có lỗi xảy ra sẽ báo lỗi cho người dùng
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        try {
            boolean isOK = quanly.xoaMaSV(txt_nhapMSV.getText());
            if (isOK == true) {
                showResult(); // Cập nhật lại giá trị bảng
                JOptionPane.showMessageDialog(this, "Đã xóa thành công sinh viên");
            } else {
                JOptionPane.showMessageDialog(this, "xóa sinh viên không thành công");
            }

        } catch (Exception e) {
            e.printStackTrace(); // báo lỗi chi tiết cho mình biết
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage()); // Thông báo trên form
        }// nếu có lỗi xảy ra sẽ báo lỗi cho người dùng
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void btn_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FindActionPerformed
        try {
            quanly.timKiemSV(txt_nhapMSV.getText());
            System.out.println(txt_nhapMSV.getText());
            if (quanly.timKiemSV(txt_nhapMSV.getText()) != -1) {

                SinhVien sv = new SinhVien();
                sv.setMaSV(txt_nhapMSV.getText());
                sv.setHoTen(txt_nhapHoTen.getText());
                sv.setTenLopNC(txt_nhapLopNC.getText());
                sv.setNgaySinh(LocalDate.of(Integer.parseInt(txt_year.getText()),
                        Integer.parseInt(txt_month.getText()),
                        Integer.parseInt(txt_date.getText())));
                sv.setQueQuan(txt_nhapQue.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Error");
            }

        } catch (Exception e) {
            e.printStackTrace(); // báo lỗi chi tiết cho mình biết
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage()); // Thông báo trên form
        }
    }//GEN-LAST:event_btn_FindActionPerformed

    // In danh sách lên bảng     
    public void showResult() {
        SinhVien s = sinhvien.get(sinhvien.size() - 1);
        tblModel.addRow(new Object[]{
            s.getMaSV(), s.getHoTen(), s.getTenLopNC(), s.getNgaySinh(), s.getQueQuan()
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinhVienJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_Find;
    private javax.swing.JButton btn_New;
    private javax.swing.JButton btn_Open;
    private javax.swing.JButton btn_Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable_InThongTinSV;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_month;
    private javax.swing.JTextField txt_nhapHoTen;
    private javax.swing.JTextField txt_nhapLopNC;
    private javax.swing.JTextField txt_nhapMSV;
    private javax.swing.JTextField txt_nhapQue;
    private javax.swing.JTextField txt_year;
    // End of variables declaration//GEN-END:variables
}
